[package]
name = "monologvm-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
bitfield = "0.16.1"
crossbeam = "0.8.4"
enum-primitive-derive = "0.3.0"
itertools = "0.13.0"
num-traits = "0.2.19"
phf = { version = "0.11.2", features = ["macros"] }
strum_macros = { version = "0.26.3" }
