[package]
name = "monologvm-pmacro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
anyhow = "1.0.89"
itertools = "0.13.0"
proc-macro2 = "1.0.86"
quote = "1.0.37"
strum_macros = { version = "0.26.4" }
syn = { version = "2.0.77", features = ["full", "extra-traits"] }
